apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: three-tier
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    # Wait for PostgreSQL to be ready
    until pg_isready -h localhost -p 5432 -U "$POSTGRES_USER"; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 2
    done

    echo "PostgreSQL is ready. Running initialization script..."

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE mydatabase;
      CREATE USER "user" WITH PASSWORD 'password';
      GRANT ALL PRIVILEGES ON DATABASE mydatabase TO "user";
    EOSQL