apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-0f6c3f870654090e5"  # Replace with your EBS Volume ID
    fsType: ext4
  storageClassName: gp2