apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: three-tier
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres