apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: three-tier
type: Opaque
data:
  username: dXNlcg==  # Base64 encoded value of 'user'
  password: cGFzc3dvcmQ=  # Base64 encoded value of 'password'