apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rsduran/three-tier-backend:8
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres"  # Use the service name from the database YAML
            - name: DB_NAME
              value: "mydatabase"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Matches the secret in the database YAML
                  key: postgres-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Matches the secret in the database YAML
                  key: postgres-password