apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rsduran/three-tier-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "three-tier-postgres-postgresql"  # The service name created by the Helm chart
            - name: DB_NAME
              value: "mydatabase"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: three-tier-postgres  # Helm chart creates a secret with the release name
                  key: postgresql-username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: three-tier-postgres  # Helm chart creates a secret with the release name
                  key: postgresql-password