name: Backend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean workspace
        run: git clean -fdx

      - name: Build Docker image
        run: |
          cd backend
          docker system prune -f
          docker container prune -f
          docker build -t rsduran/three-tier-backend:${{ github.run_number }} -f Dockerfile.backend .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push rsduran/three-tier-backend:${{ github.run_number }}

      - name: Update Kubernetes deployment
        run: |
          cd Kubernetes-Manifests/Backend
          git config user.email "reineirsamonteduran@gmail.com"
          git config user.name "rsduran"
          # Use sed to directly replace the entire line with the new image tag
          sed -i "s|image: rsduran/three-tier-backend:.*|image: rsduran/three-tier-backend:${{ github.run_number }}|" deployment.yaml
          git add deployment.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update backend image to version ${{ github.run_number }}"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Push changes if there are any
        if: success()
        run: |
          git push https://rsduran:${{ secrets.GITHUB_TOKEN }}@github.com/rsduran/three-tier-app.git || echo "No changes to push"
